version: '3.8'


# 

services:

  web:
    build: ./app
    container_name: application
    restart: always
   #command: python manage.py runserver 0.0.0.0:8000
   # ports:
    #  - 8000:8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - ./.example.docker.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres14_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=anton1
      - POSTGRES_PASSWORD=anton1
      - POSTGRES_DB=mstest1
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: anton@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static:/var/www/html/static
      - media:/var/www/html/media
    depends_on:
      - web


volumes:
  postgres_data:
  pgadmin_data:
  static:
  media:
