# Generated by Django 4.2.6 on 2023-11-05 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Ошибка критична?')),
                ('description', models.CharField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание ошибки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Ошибка отправлена на почту?')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Ошибка станка',
                'verbose_name_plural': 'Ошибки станков',
            },
        ),
        migrations.CreateModel(
            name='ErrorLogDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Ошибка критична?')),
                ('description', models.CharField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание ошибки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Ошибка отправлена на почту?')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Ошибка устройства',
                'verbose_name_plural': 'Ошибки устройства',
            },
        ),
    ]
