# Generated by Django 4.2.6 on 2023-11-05 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Название станка')),
                ('type', models.CharField(choices=[('MILLING', 'Фрезерный'), ('LATHE', 'Токарный')], verbose_name='Тип оборудования')),
                ('is_cnc', models.BooleanField(verbose_name='Станок с ЧПУ?')),
            ],
            options={
                'verbose_name': 'Станочное оборудование',
                'verbose_name_plural': 'Станочное оборудование',
            },
        ),
        migrations.CreateModel(
            name='NormDetail',
            fields=[
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machine.machine', verbose_name='Станочное оборудование')),
                ('min_qty_detail', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная выработка деталей')),
            ],
            options={
                'verbose_name': 'Норма детали',
                'verbose_name_plural': 'Норма деталей',
            },
        ),
    ]
