# Generated by Django 4.2.6 on 2023-11-05 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(primary_key=True, serialize=False, verbose_name='Мак адресс устройства')),
                ('delta', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Период измерения')),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата присоединения')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('machine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='Связанный станок')),
            ],
            options={
                'verbose_name': 'Контроллер',
                'verbose_name_plural': 'Контроллеры',
            },
        ),
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateTimeField()),
                ('end_work', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(verbose_name='Результаты измерения')),
                ('dispatch_time', models.DateTimeField(verbose_name='Время получения данных')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Числовое измерение',
                'verbose_name_plural': 'Числовые измерения',
            },
        ),
        migrations.CreateModel(
            name='MadeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_good_details', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество хороших деталей')),
                ('qty_bad_details', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество плохих деталей')),
                ('dispatch_time', models.DateTimeField(verbose_name='Время получения данных')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.CreateModel(
            name='DeviceMeasuredParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_parameter', models.CharField(choices=[('temperature', 'температура'), ('pressure', 'давление'), ('humidity', 'влажность'), ('dispatch_time', 'влажность')], verbose_name='')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Числовое измерение',
                'verbose_name_plural': 'Числовые измерения',
            },
        ),
        migrations.CreateModel(
            name='DayStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.DurationField(verbose_name='Время работы')),
                ('qty_good_details', models.IntegerField(default=0, verbose_name='Кол-во качественных деталей')),
                ('qty_bad_details', models.IntegerField(default=0, verbose_name='Кол-во плохих деталей')),
                ('max_values', models.JSONField(default={}, verbose_name='Максимальное значение')),
                ('average_values', models.JSONField(default={}, verbose_name='Среднее значение')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневные статистики',
            },
        ),
    ]
