# Generated by Django 4.2.6 on 2023-11-05 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatistics',
            name='average_values',
            field=models.JSONField(default='{}', verbose_name='Среднее значение'),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='max_values',
            field=models.JSONField(default='{}', verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='time_work',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Время работы'),
        ),
    ]
