# Generated by Django 4.2.6 on 2023-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_daystatistics_average_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatistics',
            name='average_values',
            field=models.JSONField(default=dict, verbose_name='Среднее значение'),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='max_values',
            field=models.JSONField(default=dict, verbose_name='Максимальное значение'),
        ),
    ]
