# Generated by Django 4.2.6 on 2023-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_daystatistics_average_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemeasuredparameter',
            name='measurement_system',
            field=models.CharField(default='*', verbose_name='Система измерений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicemeasuredparameter',
            name='measured_parameter',
            field=models.CharField(choices=[('temperature', 'температура'), ('pressure', 'давление'), ('humidity', 'влажность'), ('dispatch_time', 'влажность')], verbose_name='Измерямеый параметр'),
        ),
        migrations.AlterField(
            model_name='timework',
            name='end_work',
            field=models.DateTimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='timework',
            name='start_work',
            field=models.DateTimeField(verbose_name='Начало работы'),
        ),
    ]
